# Generated by Django 5.2.4 on 2025-08-05 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0008_donation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donor',
            name='eligible',
        ),
    ]
