# Generated by Django 5.2.4 on 2025-07-22 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='latitude',
            field=models.CharField(default='9.8765432', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='longitude',
            field=models.CharField(default='78.876543', max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Hospital',
        ),
    ]
