# Generated by Django 5.2.4 on 2025-07-24 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0002_location_latitude_location_longitude_delete_hospital'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_positive', models.PositiveIntegerField(default=0)),
                ('a_negative', models.PositiveIntegerField(default=0)),
                ('b_positive', models.PositiveIntegerField(default=0)),
                ('b_negative', models.PositiveIntegerField(default=0)),
                ('ab_positive', models.PositiveIntegerField(default=0)),
                ('ab_negative', models.PositiveIntegerField(default=0)),
                ('o_positive', models.PositiveIntegerField(default=0)),
                ('o_negative', models.PositiveIntegerField(default=0)),
                ('threshold', models.PositiveIntegerField(default=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bloodbank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='bloodapp.bloodbank')),
            ],
        ),
    ]
