# Generated by Django 5.2.4 on 2025-07-24 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0004_bloodrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodRequestDispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units_sent', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('RESPONDED', 'Responded'), ('DECLINED', 'Declined')], default='SENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bloodapp.bloodbank')),
                ('blood_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatches', to='bloodapp.bloodrequest')),
            ],
            options={
                'unique_together': {('blood_request', 'blood_bank')},
            },
        ),
    ]
