# Generated by Django 5.2.4 on 2025-08-02 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0007_alter_donor_donor_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('units', models.PositiveIntegerField(default=1)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('bloodbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='bloodapp.bloodbank')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='bloodapp.donor')),
            ],
        ),
    ]
