# Generated by Django 5.2.4 on 2025-07-26 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0005_bloodrequestdispatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(blank=True, editable=False, max_length=12),
        ),
    ]
