# Generated by Django 5.2.4 on 2025-07-26 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0006_donor_donor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='donor_id',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
