# Generated by Django 5.2.4 on 2025-08-10 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0009_remove_donor_eligible'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(max_length=3)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('blood_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='bloodapp.bloodbank')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='bloodapp.donor')),
            ],
        ),
    ]
