# Generated by Django 5.2.4 on 2025-09-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0010_donoralert'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_reported',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='report_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
